# Generated by Django 5.0 on 2023-12-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
