# Generated by Django 5.0.2 on 2024-04-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='new_check',
            field=models.IntegerField(default=0),
        ),
    ]
